In [ ]:
# Def function name and (parameters)
def fn(param_1):
    x = 1
    print(param_1)

fn(param_1='Hello')
fn('Hi')

Hello
Hi

In [ ]:
# Def function name and (parameters)
def fxy(x, y=9):
    print(x)
    print(y)
    print(f'The sum of {x} and {y} is {x + y}.')

fxy(y=13, x=22)
# if you don't name the parameter it will assume first value applies to first parameter
fxy(13,22)

22
13
The sum of 22 and 13 is 35.
13
22
The sum of 13 and 22 is 35.

In [5]:
# Now it's your go. Write a function, with an appropriate name
# that divides one number by the other. Bonus points if you can make the function 
# always divide the largest of the two numbers by the smallest.
# Get the function to print the answer

def div_xy(x, y):
    if x >= y:
        z = x / y
    else:
        z = y / x
    return z

answer = div_xy(y=10, x=5)

print(answer)

2.0

In [6]:
special_number = 10 # variables defined outside of functions can be used everywhere (gloabl scope)

def divide_nums_return(x, y):
    # Variables defined inside functions can only be used inside functions (local scope)
    if x > y:
        z = x / y
    else:
        z = y / x
    print(special_number)
    return z

ans = divide_nums_return(10, 100)
print(ans)

10
10.0

In [10]:
# function to add two numbers and also multiple two numbers, returning two outputs
def sum_prod(num1, num2):
    sum_12 = num1 + num2
    prod_12 = num1 * num2 

    return sum_12, prod_12

sum_30_70, prod_30_70 = sum_prod(30, 70)

print(sum_30_70)
print(prod_30_70)
print(type(sum_30_70))
print(type(prod_30_70))

100
2100
<class 'int'>
<class 'int'>

In [12]:
def sum_prod(num1, num2):
    sum_12 = num1 + num2
    prod_12 = num1 * num2 

    return sum_12, prod_12

answer = sum_prod(30, 70)

print(answer[1])
print(type(answer))

2100
<class 'tuple'>

In [ ]:
# write a function that returns x / y and x - y, 
# always dividing the biggest by the smallest number 
# and always taking the smallest from the biggest

def minus_div(x, y):
    if x >= y:
        big = x
        small = y
    else:
        big = y
        small = x
    return big / small, big - small

x_div_y, x_minus_y = minus_div(5, 10)

print(x_div_y)
print(x_minus_y)

In [ ]:
def sq(x):
    return x**2

def x_power_x(x):
    return x**x

def big_maths(x, y=None):
    if y == None:
        y = x
    return sq(x), x_power_x(y)

print(big_maths(3, 5))

In [ ]:
# In this cell, first, import the 'math' module.
# Next, write a function that squares a number (hint: you can simply uses x*x), 
# Now write a function that uses math.sqrt() to find the square root of a number 
# (hint: https://docs.python.org/3/library/math.html#math.sqrt)
# Then, write a funciton that performs both of these functions and returns both answers,
# Finally, call the function getting two variables as your answer, and print them.

import math 

def sq(x):
    return x**2

def root_fn(x):
    return math.sqrt(x)

def root_sqr_x(x):
    return sq(x), root_fn(x)

print(root_sqr_x(9))

In [13]:
import pandas as pd

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildCharacteristics.csv')

def ethnic_check(ethnicity_code):
#    if 'W' in ethnicity_code:
    if ethnicity_code[0] == "W":
        return 'White or Mixed White'
    else:
        return 'Not white'

df['background'] = df['Ethnicity'].apply(ethnic_check)

df

     Unnamed: 0        LAchildID Ethnicity            background
0             0  RND000215205141      WIRT  White or Mixed White
1             1  RND000824303014      WROM  White or Mixed White
2             2  RND000750143123      AOTH             Not white
3             3  RND000909164501      MWBC             Not white
4             4  RND000382171815      APKN             Not white
..          ...              ...       ...                   ...
327         327  RND000112711501      WOTH  White or Mixed White
328         328  RND000513120794      WROM  White or Mixed White
329         329  RND000541643134      BCRB             Not white
330         330  RND000404939452      AIND             Not white
331         331  RND000589802835      WBRI  White or Mixed White

[332 rows x 4 columns]

In [21]:
# 'https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv'
# write a function that calculates ages based on the data, and returns a new column in age range buckets
# 0-5, 6-11, 12-17, 18+

# import data
# write functions
# using conditionals
# chaqnge to date
# calculation on df columns
# making new column

df = pd.read_csv('https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv')


def bucket_maker(date_code):
    bday = pd.to_datetime(date_code, format="%Y-%m-%d")
    today = pd.to_datetime('today')

    if bday + pd.DateOffset(years=6) > today:
        return '0-5 years'
    elif bday + pd.DateOffset(years=12) > today:
        return '6-11 years'
    elif bday + pd.DateOffset(years=18) > today:
        return '12-17 years'
    else:
        return '18+'
    


df['Age Bucket'] = df['PersonBirthDate'].apply(bucket_maker)

df[['PersonBirthDate', 'Age Bucket']]

    PersonBirthDate   Age Bucket
0        2019-12-06   6-11 years
1        2011-04-27  12-17 years
2        2017-06-06   6-11 years
3        2014-10-03   6-11 years
4        2019-09-25   6-11 years
..              ...          ...
327      2010-07-07  12-17 years
328      2018-08-14   6-11 years
329      2021-12-09    0-5 years
330      2013-07-23  12-17 years
331      2021-10-25    0-5 years

[332 rows x 2 columns]